name: Python ci/cd pipeline
on: 
    push: 
        branches: 
            - main
jobs: 
    build: 
       runs-on: ubuntu-latest
       steps: 
        - name: Git checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Set up Python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.10'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: | 
            pytest