name: python-ci/cd pipeline
on: 
  push: 
    branches: 
      - main
  workflow_dispatch:
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses:  actions/setup-python@v5
        with: 
          python-version: '3.12' 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with: 
         context: .
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/python-app:${{ github.sha }}
      - name: Deploy python app in docker
        run: | 
          docker run -itd --name python-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/python-app:${{ github.sha }}
          docker ps 
          
        
